###############################################################################
# General Configuration
###############################################################################
version: 1.0.{build}

###############################################################################
# Environment Configuration
###############################################################################
image: Visual Studio 2017

configuration: 
 - Release
 - Debug
platform: 
  - x64
  - x86
environment:
  matrix:
  - solution_name: "Project 1/Project 1.sln"
  - solution_name: "Project 2/Project 2.sln"
  - solution_name: "Project 3/Project 3.sln"
  - solution_name: "Project 4/Project 4.sln"
  - solution_name: "Project 5/Project 5.sln"
  - solution_name: "Project 6/Project 6.sln"
  - solution_name: "Project 7/Project 7.sln"
  - solution_name: "Project 8/Project 8.sln"

###############################################################################
# Build Configuration
###############################################################################
build:
  parallel: true
  verbosity: normal

build_script:
  - msbuild %solution_name%
